import 'package:socket_io_client/socket_io_client.dart' as IO;
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hybrid_app/features/webrtc/providers/call_notifier.dart';
import 'package:hybrid_app/features/webrtc/models/call_state.dart';
import 'package:hybrid_app/features/session/providers/session_provider.dart'; // Import your new REST session provider

class WebRTCService {
  final Ref ref;
  IO.Socket? socket;
  RTCPeerConnection? _peerConnection;
  MediaStream? _localStream;

  WebRTCService(this.ref);

  final Map<String, dynamic> _iceConfig = {
    'iceServers': [
      {'urls': 'stun:stun.l.google.com:19302'},
    ]
  };

  /// Main method triggered when the REST API confirms a valid room session
  Future<void> startVoiceCall(String wsUrl, String roomId) async {
    ref.read(callProvider.notifier).updateStatus(CallStatus.connecting);

    try {
      // 1. Create Peer Connection FIRST to avoid race conditions with inbound socket events
      _peerConnection = await createPeerConnection(_iceConfig);

      // Listen for local network routing candidates generated by WebRTC engine
      _peerConnection!.onIceCandidate = (RTCIceCandidate candidate) {
        socket?.emit('ice-candidate', {
          'roomId': roomId, // Explicitly target the REST generated room
          'candidate': candidate.candidate,
          'sdpMid': candidate.sdpMid,
          'sdpMLineIndex': candidate.sdpMLineIndex,
        });
      };

      // Handle connection state changes natively from WebRTC engine
      _peerConnection!.onConnectionState = (RTCPeerConnectionState state) {
        if (state == RTCPeerConnectionState.RTCPeerConnectionStateConnected) {
          ref.read(callProvider.notifier).updateStatus(CallStatus.connected);
        } else if (state == RTCPeerConnectionState.RTCPeerConnectionStateFailed) {
          ref.read(callProvider.notifier).updateStatus(CallStatus.error, error: "WebRTC peer connection failed.");
        }
      };

      // 2. Safely bind Socket.io listeners now that _peerConnection exists
      _connectToSignaling(wsUrl, roomId);

      // 3. Request Microphone Hardware Access
      final Map<String, dynamic> constraints = {'audio': true, 'video': false};
      _localStream = await navigator.mediaDevices.getUserMedia(constraints);
      
      // Attach local microphone audio tracks to the peer connection pipeline
      _localStream!.getTracks().forEach((track) {
        _peerConnection!.addTrack(track, _localStream!);
      });

      // 4. Join Room Event
      // Let the signaling server know this peer is entering the REST-allocated room
      socket?.emit('join-room', {'roomId': roomId});
      
    } catch (e) {
      ref.read(callProvider.notifier).updateStatus(CallStatus.error, error: e.toString());
    }
  }

  void _connectToSignaling(String url, String roomId) {
    socket = IO.io(url, IO.OptionBuilder()
        .setTransports(['websocket'])
        .setQuery({'roomId': roomId}) // Pass room authorization payload directly
        .build());

    socket!.on('offer', (data) async {
      var description = RTCSessionDescription(data['sdp'], data['type']);
      await _peerConnection?.setRemoteDescription(description);
      await _createAnswer(roomId);
    });

    socket!.on('answer', (data) async {
      var description = RTCSessionDescription(data['sdp'], data['type']);
      await _peerConnection?.setRemoteDescription(description);
    });

    socket!.on('ice-candidate', (data) {
      _peerConnection?.addCandidate(RTCIceCandidate(
        data['candidate'],
        data['sdpMid'],
        data['sdpMLineIndex'],
      ));
    });
  }

  // 3. Handshake Execution Extensions
  Future<void> createOffer(String roomId) async {
    if (_peerConnection == null) return;
    RTCSessionDescription offer = await _peerConnection!.createOffer();
    await _peerConnection!.setLocalDescription(offer);
    socket?.emit('offer', {
      'roomId': roomId,
      'sdp': offer.sdp, 
      'type': offer.type
    });
  }

  Future<void> _createAnswer(String roomId) async {
    if (_peerConnection == null) return;
    RTCSessionDescription answer = await _peerConnection!.createAnswer();
    await _peerConnection!.setLocalDescription(answer);
    socket?.emit('answer', {
      'roomId': roomId,
      'sdp': answer.sdp, 
      'type': answer.type
    });
  }
  
  void endCall() async {
    try {
      _localStream?.getTracks().forEach((track) => track.stop());
      
      await _localStream?.dispose();
      await _peerConnection?.dispose();
      
      socket?.emit('leave-room', {'reason': 'user_ended_call'});
      socket?.disconnect();

      _localStream = null;
      _peerConnection = null;
      socket = null;

      ref.read(callProvider.notifier).updateStatus(CallStatus.disconnected);
      
      // Also clear your REST control plane state so the app knows it can take a new request
      ref.read(sessionProvider.notifier).resetSession();
      
    } catch (e) {
      ref.read(callProvider.notifier).updateStatus(CallStatus.error, error: "Failed to clean up call.");
    }
  }

  void disconnect() {
    endCall();
  }
}

// Global Provider declaration to expose this clean service to Riverpod
final webrtcServiceProvider = Provider<WebRTCService>((ref) {
  return WebRTCService(ref);
});